name: Publish Docker image

on:
  release:
    types: [published]

env:
  AWS_REGION: us-east-1

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Get the current 
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
        id: version

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          IMAGE_TAG: ${{ steps.version.outputs.tag }}
        run: |
          docker build -t public.ecr.aws/w1d9m9l9/common/action-eks-helm-deploy:${{ steps.version.outputs.tag }} .
          docker push public.ecr.aws/w1d9m9l9/common/action-eks-helm-deploy:${{ steps.version.outputs.tag }}
          echo "::set-output name=image::public.ecr.aws/w1d9m9l9/common/action-eks-helm-deploy:${{ steps.version.outputs.tag }}"
