name: Publish Docker image

on:
  release:
    types: [published]

env:
  AWS_REGION: us-east-1

jobs:
  push_to_registry:
    name: Push Docker image to Public ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3.3.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Get the current
      #   shell: bash
      #   run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      #   id: version

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: public.ecr.aws/redi-common/action-eks-helm-deploy:latest,public.ecr.aws/redi-common/action-eks-helm-deploy:${{ steps.version.outputs.tag }},ansorredikru/action-eks-helm-deploy:latest,ansorredikru/action-eks-helm-deploy:${{ steps.version.outputs.tag }}

################################################################################################################################################################################################################################################################################

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Get the current 
        shell: bash
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
        id: version

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: redi-common
          REPOSITORY: action-eks-helm-deploy
          IMAGE_TAG: ${{ steps.version.outputs.tag }}
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest
          echo "::set-output name=image::public.ecr.aws/redi-common/action-eks-helm-deploy:${{ steps.version.outputs.tag }}"
